config/routes.rb
Rails.application.routes.draw do
  resources :worktypes
  resources :tasks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "clock", to: 'clock#index', as: 'clock'
  get "dashboard", to: "dashboard#index", as: 'dashboard'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    after_create :calc_time_diff 

    has_one :worktype

    private 

    def calc_time_diff       
        prev_task = Task.where( "id < ?", id ).last
        if prev_task
            prev_task.update(time_spent: self.created_at - prev_task.created_at)
        end 
    end 

end

app/models/worktype.rb
class Worktype < ApplicationRecord
    belongs_to :task
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clock_controller.rb
class ClockController < ApplicationController
    def index 
    end 
end 

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index 
    end 
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:description, :comment)
    end
end

app/controllers/worktypes_controller.rb
class WorktypesController < ApplicationController
  before_action :set_worktype, only: %i[ show edit update destroy ]

  # GET /worktypes or /worktypes.json
  def index
    @worktypes = Worktype.all
  end

  # GET /worktypes/1 or /worktypes/1.json
  def show
  end

  # GET /worktypes/new
  def new
    @worktype = Worktype.new
  end

  # GET /worktypes/1/edit
  def edit
  end

  # POST /worktypes or /worktypes.json
  def create
    @worktype = Worktype.new(worktype_params)

    respond_to do |format|
      if @worktype.save
        format.html { redirect_to @worktype, notice: "Worktype was successfully created." }
        format.json { render :show, status: :created, location: @worktype }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @worktype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /worktypes/1 or /worktypes/1.json
  def update
    respond_to do |format|
      if @worktype.update(worktype_params)
        format.html { redirect_to @worktype, notice: "Worktype was successfully updated." }
        format.json { render :show, status: :ok, location: @worktype }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @worktype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /worktypes/1 or /worktypes/1.json
  def destroy
    @worktype.destroy
    respond_to do |format|
      format.html { redirect_to worktypes_url, notice: "Worktype was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worktype
      @worktype = Worktype.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def worktype_params
      params.require(:worktype).permit(:type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/worktypes_helper.rb
module WorktypesHelper
end

app/views/clock/index.html.erb
make a cool looking dashboard and make that pretty much the only screen you go to 
you should be able to add tasks, track them and contineu to go back to this page for almost everything 

app/views/dashboard/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-2">
        <div class="row">
            <div class="col-sidebar">
                sidebar 1
            </div>
         </div>
         <div class="row">
            <div class="col-sidebar">
                sidebar 2
            </div>
         </div>
        <div class="row">
            <div class="col-sidebar">
                sidebar 3
            </div>
         </div>
        <div class="row">
            <div class="col-sidebar">
                sidebar 4
            </div>
         </div>
        <div class="row">
            <div class="col-sidebar">
                <div class="accordion" id="accordionExample">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingOne">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Accordion Item #1
                        </button>
                        </h2>
                        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            ti
                        </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingTwo">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            Accordion Item #2
                        </button>
                        </h2>
                        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                           yo
                        </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingThree">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                            Accordion Item #3
                        </button>
                        </h2>
                        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            this
                        </div>
                        </div>
                    </div>
                </div>
            </div>
         </div>
    </div>









    <div class="col">
      2 of 2
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <%= render partial: "shared/navbar" %>
   
    <%= yield %>







    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"><%= link_to "Clock", clock_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Dashboard", dashboard_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Tasks", tasks_path, class: "nav-link"  %></li>
        <li class="nav-item"><%= link_to "Worktypes", worktypes_path, class: "nav-link"  %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>

  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>




  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Description</th>
      <th>Comment</th>
      <th>Time Spent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.created_at.strftime("%m/%d/%Y") %></td>
        <td><%= task.created_at.strftime("%I:%M%p") %></td>
        <td><%= task.description %></td>
        <td><%= task.comment %></td>
        <td><%= time_ago_in_words((task.time_spent.to_f/60).minutes.from_now) if task.time_spent %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p><strong>Description: </strong><%= @task.description %></p>
<p><strong>Comment: </strong><%= @task.comment %></p>
<p><strong>Date: </strong><%= @task.created_at.strftime("%m/%d/%Y") %></p>
<p><strong>Time: </strong><%= @task.created_at.strftime("%I:%M%p") %></p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/worktypes/_form.html.erb
<%= form_with(model: worktype) do |form| %>
  <% if worktype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worktype.errors.count, "error") %> prohibited this worktype from being saved:</h2>

      <ul>
        <% worktype.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/worktypes/edit.html.erb
<h1>Editing Worktype</h1>

<%= render 'form', worktype: @worktype %>

<%= link_to 'Show', @worktype %> |
<%= link_to 'Back', worktypes_path %>

app/views/worktypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Worktypes</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @worktypes.each do |worktype| %>
      <tr>
        <td><%= worktype.type %></td>
        <td><%= link_to 'Show', worktype %></td>
        <td><%= link_to 'Edit', edit_worktype_path(worktype) %></td>
        <td><%= link_to 'Destroy', worktype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Worktype', new_worktype_path %>

app/views/worktypes/new.html.erb
<h1>New Worktype</h1>

<%= render 'form', worktype: @worktype %>

<%= link_to 'Back', worktypes_path %>

app/views/worktypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @worktype.type %>
</p>

<%= link_to 'Edit', edit_worktype_path(@worktype) %> |
<%= link_to 'Back', worktypes_path %>